#!/usr/bin/env python3
"""
Generates LocalBusiness JSON-LD from seo/business.json and injects the same
block into the <head> of every top-level .html file in the project.

This is a plain static HTML site (no templating engine, no shared layout
file), so "the main layout head" means every page's own <head> — this
script keeps them all in sync from one config file instead of hand-editing
each one.

Usage:
    python3 scripts/generate_schema.py

Re-run any time seo/business.json changes. Safe to run repeatedly: it
looks for the BEGIN/END marker comments and replaces only what's between
them, so it won't duplicate the block or disturb anything else in <head>.
"""
import json
import re
from pathlib import Path
from urllib.parse import urljoin

ROOT = Path(__file__).resolve().parent.parent
CONFIG_PATH = ROOT / "seo" / "business.json"

BEGIN_MARKER = "<!-- BEGIN LOCALBUSINESS SCHEMA (auto-generated by scripts/generate_schema.py — edit seo/business.json instead) -->"
END_MARKER = "<!-- END LOCALBUSINESS SCHEMA -->"


def build_schema(config: dict) -> dict:
    """Map the config file onto a schema.org LocalBusiness dict, omitting
    any field that's empty rather than publishing a placeholder value."""
    url = config.get("url", "").strip()
    logo_path = config.get("logoPath", "").strip()
    logo_url = urljoin(url, logo_path) if url and logo_path else (logo_path or None)

    schema = {
        "@context": "https://schema.org",
        "@type": "LocalBusiness",
        "name": config.get("name") or None,
        "description": config.get("description") or None,
        "url": url or None,
        "logo": logo_url,
        "image": logo_url,
        "telephone": config.get("telephone") or None,
        "email": config.get("email") or None,
    }

    founder_name = config.get("founderName", "").strip()
    if founder_name:
        schema["founder"] = {"@type": "Person", "name": founder_name}

    address_fields = {
        "streetAddress": config.get("streetAddress", "").strip(),
        "addressLocality": config.get("addressLocality", "").strip(),
        "addressRegion": config.get("addressRegion", "").strip(),
        "postalCode": config.get("postalCode", "").strip(),
        "addressCountry": config.get("addressCountry", "").strip(),
    }
    address_fields = {k: v for k, v in address_fields.items() if v}
    if address_fields:
        schema["address"] = {"@type": "PostalAddress", **address_fields}

    same_as = [s for s in config.get("sameAs", []) if s.strip()]
    if same_as:
        schema["sameAs"] = same_as

    # Drop any top-level key that ended up None/empty.
    return {k: v for k, v in schema.items() if v not in (None, "", [], {})}


def build_block(schema: dict) -> str:
    json_ld = json.dumps(schema, indent=2, ensure_ascii=False)
    return (
        f"{BEGIN_MARKER}\n"
        f'<script type="application/ld+json">\n{json_ld}\n</script>\n'
        f"{END_MARKER}"
    )


def inject(html: str, block: str) -> str:
    pattern = re.compile(
        re.escape(BEGIN_MARKER) + r".*?" + re.escape(END_MARKER), re.DOTALL
    )
    if pattern.search(html):
        return pattern.sub(block, html)
    # No existing block: insert right before </head>.
    return html.replace("</head>", f"{block}\n</head>", 1)


def main():
    config = json.loads(CONFIG_PATH.read_text())
    schema = build_schema(config)
    block = build_block(schema)

    html_files = sorted(ROOT.glob("*.html"))
    for path in html_files:
        original = path.read_text()
        updated = inject(original, block)
        if updated != original:
            path.write_text(updated)
            print(f"updated: {path.name}")
        else:
            print(f"unchanged: {path.name}")

    print(f"\n{len(html_files)} page(s) processed.")


if __name__ == "__main__":
    main()
